blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:post_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('portfolio/', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from portfolio import views

app_name = 'portfolio'

urlpatterns = [
    path('<int:project_id>/', views.project_detail, name='project_detail'),
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    message = models.TextField(max_length=300)
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def all_blogs(request):
    posts = Post.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'posts':posts})

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html', {'post':post})

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects' : projects})

def blog(request):
    return render(request, 'personal_portfolio-project/blog/templates/blog/all_blogs.html')

def project_detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'portfolio/project_detail.html', {'project':project})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<center><h2>Тут написано {{ posts.count }} постов</h2></center>

  {% for post in posts %}

    <a href="{% url 'blog:detail' post.id %}"><h3>{{ post.title }}</h3></a>

    <p>{{ post.date }}</p>

    <h5>{{ post.message|safe|truncatechars:100 }}</h5>

  {% endfor %}

    {% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<center><h1>{{ post.title }}</h1></center>

<center><p>{{ post.date }}</p></center>

<h3>{{ post.message|safe }}</h3>

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>

  {% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static "portfolio/icon_empty.png" %}">
    <title>Сайт Ермилова Артема</title>
  </head>

  <body>
  <div style="margin-left:20px; margin-right:20px;">

  <ul class="nav justify-content-end">
    <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'blog:all_blogs' %}">Мой блог</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'blog:all_blogs' %}">Мой блог</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://vk.com/id115033320">Вконтакте</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://t.me/tema_ermilov">Telegram</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}">Резюме</a>
  </li>
</ul>

  <a href="{% url 'home' %}"><h3><img src="{% static 'portfolio/icon_empty.png' %}" height="50"> Сайт Ермилова Артема</h3></a>

    {% block content %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</div>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}

<p class="aligncenter">
    <img src="{% static 'portfolio/self.jpg' %}" height="400">
</p>
<style>
.aligncenter {
    text-align: center;
}
</style>
    <center><h2>Привет, этот сайт я создал с помощью Django 3. Изучал данную тему я по курсу Ника Уолтера.</h2></center>

 <center><h4 class="mt-5">Мои проекты:</h4></center>

<hr>

<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}"  target="_blank">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <a href="{% url 'portfolio:project_detail' project.id %}"><h3>{{ project.title }}</h3></a>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}

portfolio/templates/portfolio/project_detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>{{ project.title }}</h1>

<h3>{{ project.description|safe }}</h3>

{% endblock %}